<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Stringy\\' => array($vendorDir . '/danielstjules/stringy/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Mohiohio\\WordPress\\' => array($vendorDir . '/mohiohio/wordpress-lib/src'),
    'GraphQL\\' => array($vendorDir . '/webonyx/graphql-php/src'),
    'CI\\GraphQLWP\\' => array($baseDir . '/'),
);
